from .numeral_space import NaturalSearchSpace, ContinueSearchSpace
from .tensor_space import TensorSearchSpace
from .categorical_search_space import BooleanSearchSpace, CategoricalSearchSpace
from .class_factory_space import ClassFabricSearchSpace
