from search_space.spaces.search_space import SearchSpace, Function, SearchSpaceDomain
from search_space.spaces.ast_constraint import UniversalVariableInstance as UniversalVariable
from search_space.spaces.ast_index import UniversalIndexInstance as UniversalIndex
